{"level": "DEBUG", "message": "debug message", "timestamp": "2024-01-23T15:20:53.151737+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 25, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2024-01-23T15:20:53.151737+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 26, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2024-01-23T15:20:53.151737+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2024-01-23T15:20:53.152735+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2024-01-23T15:20:53.152735+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message", "timestamp": "2024-01-23T15:20:53.152735+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 33, "thread_name": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\James\\PycharmProjects\\VideosSampleCode\\videos\\135_modern_logging\\main.py\", line 31, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2025-07-18T20:51:50.190431+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 25, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2025-07-18T20:51:50.190431+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 26, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-07-18T20:51:50.190431+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-07-18T20:51:50.190431+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2025-07-18T20:51:50.190930+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message", "timestamp": "2025-07-18T20:51:50.190930+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 33, "thread_name": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Users\\Saloc\\Desktop\\135_modern_logging\\main.py\", line 31, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero"}
{"level": "DEBUG", "message": "this is such a special case of logging idk", "timestamp": "2025-07-18T20:58:54.026676+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2025-07-18T21:00:15.364584+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 25, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2025-07-18T21:00:15.365085+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 26, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "this is such a special case of logging idk", "timestamp": "2025-07-18T21:00:15.365085+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-07-18T21:00:15.365085+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-07-18T21:00:15.365085+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2025-07-18T21:00:15.365085+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message\nTraceback (most recent call last):\n  File \"c:\\Users\\Saloc\\Desktop\\135_modern_logging\\main.py\", line 32, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2025-07-18T21:00:15.365085+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 34, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2025-07-18T21:00:19.457259+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 25, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2025-07-18T21:00:19.457259+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 26, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "this is such a special case of logging idk", "timestamp": "2025-07-18T21:00:19.457259+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-07-18T21:00:19.457259+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-07-18T21:00:19.457758+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2025-07-18T21:00:19.457758+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message\nTraceback (most recent call last):\n  File \"c:\\Users\\Saloc\\Desktop\\135_modern_logging\\main.py\", line 32, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2025-07-18T21:00:19.457758+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 34, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2025-07-18T21:02:12.317137+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 25, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2025-07-18T21:02:12.317640+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 26, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "this is such a special case of logging idk", "timestamp": "2025-07-18T21:02:12.317640+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-07-18T21:02:12.317640+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-07-18T21:02:12.317640+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2025-07-18T21:02:12.317640+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message\nTraceback (most recent call last):\n  File \"c:\\Users\\Saloc\\Desktop\\135_modern_logging\\main.py\", line 32, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2025-07-18T21:02:12.317640+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 34, "thread_name": "MainThread"}
